--- 
- name: Verify 
  ios_command: 
    commands: 
      - show run | section hostname 
  register: name 
- name: Correct 
  debug: 
    msg: 
      - Your hostname configuration is correct 
      - Your hostname configuration is 
      - R1 
      - And router hostname is 
      - "{{ name.stdout_lines[0][0].split()[1] }}" 
  when: name.stdout_lines[0][0].split()[1] == "R1" 
- name: Incorrect 
  debug: 
    msg: 
      - Your hostname configuration is incorrect 
      - Your hostname configuration is 
      - R1 
      - But router hostname is 
      - "{{ name.stdout_lines[0][0].split()[1] }}" 
  when: name.stdout_lines[0][0].split()[1] != "R1"