---
- name: Configure ospf protocol
  ios_config:
    lines:
      - network {{ prefix }} 0.0.0.0 area {{ area }}
    parents: 
      - router ospf {{ ps_id }}
#- name: test
#  debug:
#    msg:
#      - network {{ item }}
#  with_items:
#    - "{{ test.split('\n') }}"
 
   
