---

- name: Remove Verify.yml
  file:
    path: /var/lib/awx/projects/New_Switch/Verify/roles/vtp_mode_domain/tasks/Verify.yml
    state: absent

- name: Touch Verify.yml
  file:
    path: /var/lib/awx/projects/New_Switch/Verify/roles/vtp_mode_domain/tasks/Verify.yml
    state: touch
    mode: u=rw,g=r,o=r
    
- name: Copy contents to Verify.yml 
  copy:
    content:
      "--- 
      \n- name: Verify vtp mode
      \n  ios_command:  
      \n    commands:
      \n      - show vtp status | section Operating
      \n  register: mode
      \n- name: Verify vtp domain
      \n  ios_command:
      \n    commands:
      \n      - show vtp status | section Domain
      \n  register: domain
      \n- name: Correct(mode)
      \n  debug:
      \n    msg:
      \n      - Your vtp mode configuration is correct
      \n      - Your vtp mode configuration is
      \n      - {{ mode }}
      \n      - And output from switch is
      \n      - {% raw %}\"{{ mode.stdout_lines[0][0].split()[4] }}\"{% endraw %}
      \n  when: mode.stdout_lines[0][0].split()[4] == \"{{ mode }}\"
      \n- name: Correct(domain)
      \n  debug:
      \n    msg:
      \n      - Your vtp domain configuration is correct
      \n      - Your vtp domain configuration is
      \n      - {{ domain }}
      \n      - And output from switch is
      \n      - {% raw %}\"{{ domain.stdout_lines[0][0].split()[4] }}\"{% endraw %}
      \n  when: domain.stdout_lines[0][0].split()[4] == \"{{ domain }}\"
      \n- name: Incorrect(mode)
      \n  debug:
      \n    msg:
      \n      - Your vtp mode configuration is incorrect
      \n      - Your vtp mode configuration is
      \n      - {{ mode }}
      \n      - But output from switch is
      \n      - {% raw %}\"{{ mode.stdout_lines[0][0].split()[4] }}\"{% endraw %}
      \n  when: mode.stdout_lines[0][0].split()[4] != \"{{ mode }}\"
      \n- name: Incorrect(domain)
      \n  debug:
      \n    msg:
      \n      - Your vtp mode configuration is incorrect
      \n      - Your vtp mode configuration is
      \n      - {{ domain }}
      \n      - But output from switch is
      \n      - {% raw %}\"{{ domain.stdout_lines[0][0].split()[4] }}\"{% endraw %}
      \n  when: domain.stdout_lines[0][0].split()[4] != \"{{ domain }}\""
    dest: /var/lib/awx/projects/New_Switch/Verify/roles/vtp_mode_domain/tasks/Verify.yml
