--- 
- name: Verify 
  ios_command: 
    commands: 
      - show run | section hostname 
  register: name 
- name: Output
  debug: 
    msg: 
      - Router hostname is 
      - "{{ name.stdout_lines[0][0].split()[1] }}"
