---

- hosts: "{{ host_ip }}"
  gather_facts: no
  
  roles:
    - {role: hostname, when: hostname is defined and hostname != ""}
    - {role: interface_ip, when: ip is defined and ip != ""}
    - {role: interface_status, when: up_or_down is defined }

   
 
