--- 
- name: Python Execution
#  IPtoNetwork: 
#    ip: 1.1.1.1
#    mask: 255.0.0.0
  checkClassful:
    ip: 192.168.100.5
  register: mask
- name: IP to classful
  IPtoNetwork:
    ip: 192.168.100.5
    mask: "{{ mask.msg }}"
  register: result
- debug: var=result.msg
